        runtime: python39 # Especifica la versi칩n de Python. Python 3.9 es estable y compatible.
        entrypoint: gunicorn -b :$PORT backend:app

        instance_class: F1 # Tipo de instancia. F1 es la m치s peque침a y suele ser suficiente para el nivel gratuito.

        handlers:
        - url: /.*
          script: auto
          secure: always # Redirige todo el tr치fico a HTTPS
        